server{
    listen 80;
    server_tokens off;

    add header X-Content-Type-Options "nosniff" always;
    add header X-Frame-Options "DENY" always;
    add header Referrer-Policy "strict-origin-when-cross-origin" always;

    gzip on;
    gzip_types text/plain test/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1024;

    location / {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|css|woff2?|ttf|svg|png|jpg|jpeg|gif|ico)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
