sonar.projectKey=COS301-SE-2026_Hackathon-Platform
sonar.organization=cos301-se-2026
sonar.host.url=https://sonarcloud.io
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test,frontend/src
sonar.exclusions=frontend/src/app/component-tests/**
sonar.sourceEncoding=UTF-8