-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

CREATE TABLE roles (
	role_id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	description TEXT
);

CREATE TABLE permissions (
	id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	description TEXT
);

CREATE TABLE rolepermissions (
	role_id SMALLINT NOT NULL,
	permission_id SMALLINT NOT NULL,
	PRIMARY KEY (role_id, permission_id),

	CONSTRAINT fk_role_permissions_role
		FOREIGN KEY (role_id)
		REFERENCES roles(role_id)
		ON DELETE CASCADE,

	CONSTRAINT fk_role_permissions_permission
		FOREIGN KEY (permission_id)
		REFERENCES permissions(id)
		ON DELETE CASCADE
);

CREATE TABLE users (
	user_id UUID PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	role_id SMALLINT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

	CONSTRAINT fk_user_role
		FOREIGN KEY (role_id)
		REFERENCES roles(role_id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_users_status
		CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE events (
	event_id UUID PRIMARY KEY,
	created_by_user_id UUID NOT NULL,
	name VARCHAR(100) NOT NULL,
	registration_key VARCHAR(50),
	team_size_limit SMALLINT NOT NULL,
	start_datetime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	duration INT NOT NULL,
	description TEXT,
	visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
	status VARCHAR(30) NOT NULL DEFAULT 'INACTIVE',

	CONSTRAINT fk_events_created_by_user
		FOREIGN KEY (created_by_user_id)
		REFERENCES users(user_id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_events_team_size_limit
		CHECK (team_size_limit > 0),

	CONSTRAINT chk_events_duration
		CHECK (duration > 0),

	CONSTRAINT chk_events_status
		CHECK (status IN ('ACTIVE', 'INACTIVE', 'COMPLETED', 'CANCELED')),

	CONSTRAINT chk_events_visibility
		CHECK (visibility IN ('PUBLIC', 'PRIVATE')),

	CONSTRAINT chk_events_registration_key
		CHECK (
			visibility = 'PUBLIC'
			OR registration_key IS NOT NULL
		)
);

CREATE TABLE teams (
	team_id UUID PRIMARY KEY,
	team_name VARCHAR(100) NOT NULL,
	created_by_user_id UUID NOT NULL,
	event_id UUID NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

	CONSTRAINT fk_teams_created_by_user
		FOREIGN KEY (created_by_user_id)
		REFERENCES users(user_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_teams_event_id
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_teams_status
		CHECK (status IN ('ACTIVE', 'INACTIVE')),

	CONSTRAINT uq_teams_event_team_name
		UNIQUE (event_id, team_name)
);

CREATE TABLE teammembers (
	team_member_id UUID PRIMARY KEY,
	team_id UUID NOT NULL,
	user_id UUID NOT NULL,
	joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

	CONSTRAINT fk_teamMembers_user_id
		FOREIGN KEY (user_id)
		REFERENCES users(user_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_teamMembers_team_id
		FOREIGN KEY (team_id)
		REFERENCES teams(team_id)
		ON DELETE CASCADE,

	CONSTRAINT chk_teammembers_status
		CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'INACTIVE', 'LEFT', 'REMOVED')),

	CONSTRAINT uq_teammember_team_user
		UNIQUE (team_id, user_id)
);

CREATE TABLE eventregistrations (
	registration_id UUID PRIMARY KEY,
	event_id UUID NOT NULL,
	team_id UUID NOT NULL,
	registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

	CONSTRAINT fk_eventregistrations_team_id
		FOREIGN KEY (team_id)
		REFERENCES teams(team_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_eventregistrations_event_id
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_eventregistrations_status
		CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED')),

	CONSTRAINT uq_eventregistrations_event_id_team_id
		UNIQUE (event_id, team_id)
);

CREATE TABLE levels (
	id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	event_id UUID NOT NULL,
	name VARCHAR(200) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	level_number SMALLINT NOT NULL,
	description TEXT,

	CONSTRAINT fk_levels_event_id
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_levels_number
		CHECK (level_number > 0),

	CONSTRAINT uq_levels_event_level_number
		UNIQUE (event_id, level_number)
	
);

CREATE TABLE levelfiles (
	id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	level_id SMALLINT NOT NULL,
	file_name TEXT NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	storage_key TEXT NOT NULL,
	file_type VARCHAR(20) NOT NULL,

	CONSTRAINT fk_levelfiles_level_id
		FOREIGN KEY (level_id)
		REFERENCES levels(id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_levelfiles_file_type
		CHECK (file_type IN ('ZIP', 'TAR', 'PDF', 'TXT', 'CSV', 'JSON', 'IMAGE', 'OTHER'))
);

CREATE TABLE solverversion (
	id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	event_id UUID NOT NULL,
	uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	uploaded_by UUID NOT NULL,
	notes TEXT,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	storage_key TEXT NOT NULL,

	CONSTRAINT fk_solverversion_event_id
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_solverversion_uploaded_by
		FOREIGN KEY (uploaded_by)
		REFERENCES users(user_id)
		ON DELETE RESTRICT
);

CREATE TABLE submissions (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	team_id UUID NOT NULL,
	level_id SMALLINT NOT NULL,
	solver_version_id SMALLINT NOT NULL,
	score NUMERIC(10,2) NOT NULL DEFAULT 0,
	status VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
	submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	source_code_storage_key TEXT NOT NULL,
	output_storage_key TEXT NOT NULL,

	CONSTRAINT fk_submissions_level_id
		FOREIGN KEY (level_id)
		REFERENCES levels(id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_submissions_team_id
		FOREIGN KEY (team_id)
		REFERENCES teams(team_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_submissions_solver_version_id
		FOREIGN KEY (solver_version_id)
		REFERENCES solverversion(id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_submissions_status
		CHECK (status IN('QUEUED', 'SCORING', 'SCORED', 'FAILED', 'CANCELED')),

	CONSTRAINT chk_submissions_score
		CHECK (score >= 0)
);

CREATE TABLE scoringlogs (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	submission_id BIGINT NOT NULL,
	log_text TEXT NOT NULL,
	error_type VARCHAR(50),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_scoringlogs_submission_id
		FOREIGN KEY (submission_id)
		REFERENCES submissions(id)
		ON DELETE RESTRICT
	
);

CREATE TABLE leaderboardentries (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	team_id UUID NOT NULL,
	level_id SMALLINT NOT NULL,
	event_id UUID NOT NULL,
	best_score NUMERIC(10,2) NOT NULL DEFAULT 0,
	best_submission_id BIGINT,
	last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_leaderboardentries_team_id
		FOREIGN KEY (team_id)
		REFERENCES teams(team_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_leaderboardentries_level_id
		FOREIGN KEY (level_id)
		REFERENCES levels(id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_leaderboardentries_event_id
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_leaderboardentries_best_score
		CHECK (best_score >= 0),

	CONSTRAINT fk_leaderboardentries_best_submission_id
		FOREIGN KEY (best_submission_id)
		REFERENCES submissions(id)
		ON DELETE RESTRICT,

	CONSTRAINT uq_leaderboardentries_event_level_team
		UNIQUE(event_id, level_id, team_id)
);

CREATE TABLE qaquestions (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	event_id UUID NOT NULL,
	user_id UUID NOT NULL,
	level_id SMALLINT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	question_text TEXT NOT NULL,
	is_pinned BOOLEAN NOT NULL DEFAULT FALSE,

	CONSTRAINT fk_qaquestions_event_id
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_qaquestions_user_id
		FOREIGN KEY (user_id)
		REFERENCES users(user_id)
		ON DELETE RESTRICT,
		
	CONSTRAINT fk_qaquestions_level_id
		FOREIGN KEY (level_id)
		REFERENCES levels(id)
		ON DELETE RESTRICT
);

CREATE TABLE qaanswers (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id UUID NOT NULL,
	question_id BIGINT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	answer_text TEXT NOT NULL,

	CONSTRAINT fk_qaanswers_user_id
		FOREIGN KEY (user_id)
		REFERENCES users(user_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_qaanswers_question_id
		FOREIGN KEY (question_id)
		REFERENCES qaquestions(id)
		ON DELETE RESTRICT
);

CREATE TABLE emailcommunication (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	event_id UUID NOT NULL,
	recipient_type VARCHAR(20) NOT NULL DEFAULT 'OTHER',
	subject VARCHAR(255) NOT NULL,
	body TEXT NOT NULL,
	sent_by UUID NOT NULL,
	sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT fk_emailcommunication_event_id
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE RESTRICT,

	CONSTRAINT fk_emailcommunication_user_id
		FOREIGN KEY (sent_by)
		REFERENCES users(user_id)
		ON DELETE RESTRICT,

	CONSTRAINT chk_emailcommunication_recipient_type
		CHECK (recipient_type IN('ALL_USERS', 'EVENT_PARTICIPANTS', 'ADMIN', 'PARTICIPANT', 'OTHER'))
);